spring:
  application:
    name: ai-super-gaent
  profiles:
    active: local
#  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: gemma3:1b
  ai:
    ollama:
      chat:
        enabled: false
      embedding:
        enabled: false
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:8127
#        stdio:
#          servers-configuration: classpath:mcp-servers.json

  datasource:
    url: jdbc:postgresql://rm-cn-2rn4e9j4d000a5ho.rwlb.rds.aliyuncs.com:5432/Bo_ai_agent
    username: Defector
    password: BJHb151678
    ai:
      vectorstore:
        pgvector:
          index-type: HNSW
          dimensions: 1536
          distance-type: COSINE_DISTANCE
          max-document-batch-size: 10000 # Optional: Maximum number of documents per batch



server:
  port: 8123
  servlet:
    context-path: /api


# springdoc-openapi 接口文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.bjh.aisuperagent.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# search api key
search-api:
  api-key: PREBjxUCHFWPtyymmCmZQWE8